### ISSUE TITLE
Text in EditView buttons is not centered

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#2]
![buttontextnotcentered](https://cloud.githubusercontent.com/assets/1237191/17462908/c5a6eb66-5cbb-11e6-975d-b239400b7fa3.png)

**Comment by Luke1982** [comment]
I've noticed, will fix.

**Comment by Luke1982** [comment]
This issue is actually related to native CRM behaviour: the template has a fixed width set on these buttons, as you can see [here](https://github.com/tsolucio/corebos/blob/master/Smarty/templates/CreateView.tpl#L142-L143). Best way to fix this in my opinion is just to remove this hardcoded width.

**Comment by joebordes** [comment]
that sounds ok, make a PR and I will accept
remember to modify also salesEditView.tpl and the same button at the end of the form

**Comment by Luke1982** [comment]
[Done](https://github.com/tsolucio/corebos/pull/84)

**Comment by Luke1982** [comment]
Still something is wrong. I altered the files, but there is still a fixed width when I edit a salesorder. There must be another file that needs the edit.

**Comment by joebordes** [comment]
let me know when you got it and update the PR accordingly

**Comment by Luke1982** [comment]
Please check my brand new PR. I closed the initial one, completely removed my old corebos fork, forked a new one and followed your advised path.

**Comment by Luke1982** [comment]
Please ignore the PR, I don't know how but some old version of the file  Smarty/templates/Inventory/InventoryDetailView.tpl came into it.

**Comment by joebordes** [comment]
Perfect!!
Your getting it :-)
