### ISSUE TITLE
No border in quantity field of inventory modules

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#3]
When focus is set in quantity field if the inventory lines the box is lost and you don't know where the cursor/focus is.

![inventorylinesqtyloseboxreference](https://cloud.githubusercontent.com/assets/1237191/17462924/f86041c4-5cbb-11e6-9b45-0db769c85640.png)

**Comment by Luke1982** [comment]
Noticed and on list.

**Comment by Luke1982** [comment]
For this I would like to propose the following [commit](https://github.com/Luke1982/corebos/commit/a2bf267c29b5abf5f1ea73b51df85ad9825e2b94). There are two reasons to do it this way:
- It fixes the issue you addressed.
- Adding a class through an onfocus attribute really is IE6 material. Modern browsers have far better ways of handling this via CSS3. Better even still would be to add a classname to the input fields so you can target them (and their states) through CSS, which is the modern way. Let me know how you feel about this.

**Comment by joebordes** [comment]
I added that commit to coreBOS and it works perfect.
Thanks!
