### ISSUE TITLE
Jump To box background is transparent

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#4]
or z-index is wrong....

![jumptooverlayzindex](https://cloud.githubusercontent.com/assets/1237191/17462929/2189ef6e-5cbc-11e6-95bc-b19b026f86a2.png)

**Comment by Luke1982** [comment]
Hadn't noticed yet, thanks for the tip!

**Comment by Luke1982** [comment]
Fixed.
