### ISSUE TITLE
Show/Hide images are wrong on related lists

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#5]
![togglerelatedlistbuttons](https://cloud.githubusercontent.com/assets/1237191/17462934/410ab468-5cbc-11e6-8222-5d9d56860610.png)

**Comment by Luke1982** [comment]
Hmm, weird. This is not so on my develop install. Let me dive into this.

**Comment by joebordes** [comment]
Update your coreBOS code to the latest commit, maybe it is something I missed in the manual merge

**Comment by Luke1982** [comment]
Fixed in [this ](https://github.com/Luke1982/mltheme-corebos/commit/506cfbd9bbafcf0f9937ed21f4f09b8e64ca4dbf) commit. Although I don't like the over-use of '!important', it is necessary since so much style is hard-coded.
