### ISSUE TITLE
Show Related List Icon Lost

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#7]
I was working with the Softed theme yesterday and saw an error which has appeared due to one of the class changes we made.

When you click on Full Hide Related List the open/show icon disappears.

![showrelatedlisticonlost](https://cloud.githubusercontent.com/assets/1237191/17675773/7d710810-632b-11e6-9961-92ca9ad24701.png)

I traced it a little. It is because the class exp_coll_block is display:none so, although the code does a show of the icon, since it is inside the span with the class you can't see it. This works correctly in your theme so I would like to know how you accomplish that so I can do the same in the other themes.

https://github.com/tsolucio/corebos/blob/master/Smarty/templates/RelatedListContents.tpl#L135

Thanks for any help and guidance

**Comment by Luke1982** [comment]
I created an icon font and set the arrow character as the "before" [element](https://github.com/Luke1982/mltheme-corebos/blob/master/style.css#L430-L446). You could do something like replacing the content of the "before" elements style with:

```
display: inline-block;
width: 0;
height: 0;
border-style: solid;
border-width: 0 8px 8px 8px;
border-color: transparent transparent #ffffff transparent;
```

The updated JS should update the class to either 'active' or 'inactive'. You can generate any triangle [here](http://apps.eky.hk/css-triangle-generator/). Hope this helps to get it working.

Anyway tricks like these generally help, modern browsers won't download images that have a 'display: none' attribute, so this should help increase performance.

**Comment by joebordes** [comment]
Got it.
Thanks!!

https://github.com/tsolucio/corebos/commit/33da6073d8498c8e26339a925c5aa9e784f60cc1
