### ISSUE TITLE
z-index in tax and discount popups Inventory Modules

### ISSUE THREAD

**Issue by omarllorens** [Luke1982/mltheme-corebos#8]
Hi, I've found the next error on inventory modules, when you clicked to tax or discounts and show you the popup. These divs are under the rest of content, seems that need to add a z-index to discountUI class.
![seleccion_503](https://cloud.githubusercontent.com/assets/7083757/18511113/3b81ba6c-7a82-11e6-9b6d-474a10a0b0e4.png)

**Comment by Luke1982** [comment]
Ah, yes. This probably is a z-index issue as you suggested. Thanks for reporting, I'll put it on my list.

**Comment by Luke1982** [comment]
Fixed [here](https://github.com/Luke1982/mltheme-corebos/commit/8a4115f64ed63cff85adb2498598b75593b4ab47)

**Comment by omarllorens** [comment]
Thanks!
